//! Persistence implementations

pub mod memory;
#[cfg(feature = "postgres")]
pub mod postgres;
#[cfg(feature = "postgres")]
pub mod database;
#[cfg(feature = "postgres")]
pub mod user_repository;
#[cfg(feature = "postgres")]
pub mod cdr_repository;
#[cfg(feature = "postgres")]
pub mod role_repository;
#[cfg(feature = "postgres")]
pub mod conference_repository;
#[cfg(feature = "postgres")]
pub mod voicemail_repository;
#[cfg(feature = "postgres")]
pub mod call_queue_repository;
#[cfg(feature = "postgres")]
pub mod tenant_repository;
#[cfg(feature = "postgres")]
pub mod sip_trunk_repository;

#[cfg(feature = "postgres")]
pub use database::{create_pool, run_migrations, DatabaseConfig};
#[cfg(feature = "postgres")]
pub use user_repository::PgUserRepository;
#[cfg(feature = "postgres")]
pub use cdr_repository::PgCdrRepository;
#[cfg(feature = "postgres")]
pub use role_repository::PgRoleRepository;
#[cfg(feature = "postgres")]
pub use conference_repository::PgConferenceRepository;
#[cfg(feature = "postgres")]
pub use voicemail_repository::PgVoicemailRepository;
#[cfg(feature = "postgres")]
pub use call_queue_repository::PgCallQueueRepository;
#[cfg(feature = "postgres")]
pub use tenant_repository::PgTenantRepository;
#[cfg(feature = "postgres")]
pub use sip_trunk_repository::PgSipTrunkRepository;
